# PiCalendar 設定ファイル (サンプル)
# このファイルを settings.yaml にコピーして使用してください
# cp settings.example.yaml settings.yaml

# 画面設定
screen:
  width: 1024              # 画面幅（ピクセル）
  height: 600              # 画面高さ（ピクセル）
  fps: 30                  # フレームレート
  fullscreen: true         # フルスクリーン表示
  hide_cursor: true        # マウスカーソルを隠す

# レイアウト設定（ウィジェットの配置）
layout:
  clock:
    position: "top-center"    # 位置（top-left, top-center, top-right, center, bottom-left, bottom-center, bottom-right）
    x_offset: 0               # X座標の微調整（ピクセル）
    y_offset: 100             # Y座標の微調整（ピクセル）
  date:
    position: "top-center"    # 位置
    x_offset: 0               # X座標の微調整
    y_offset: 240             # Y座標の微調整
  calendar:
    position: "bottom-right"  # 位置
    x_offset: -30             # X座標の微調整
    y_offset: -30             # Y座標の微調整
  weather:
    position: "bottom-left"   # 位置
    x_offset: 30              # X座標の微調整
    y_offset: -30             # Y座標の微調整
  moon_phase:
    position: "top-right"     # 位置
    x_offset: -50             # X座標の微調整
    y_offset: 50              # Y座標の微調整

# UI設定
ui:
  margins:
    x: 24                  # 左右マージン
    y: 16                  # 上下マージン
  clock_font_px: 130       # 時計のフォントサイズ
  date_font_px: 36         # 日付のフォントサイズ
  cal_font_px: 22          # カレンダーのフォントサイズ（旧名）
  calendar_font_px: 22     # カレンダーのフォントサイズ
  weather_font_px: 22      # 天気のフォントサイズ
  colors:
    text: [255, 255, 255]       # 通常テキスト色
    sunday: [255, 100, 100]     # 日曜日の色
    saturday: [100, 100, 255]   # 土曜日の色
    weekday: [255, 255, 255]    # 平日の色
    holiday: [255, 80, 80]      # 祝日の色
    background: [0, 0, 0]       # 背景色
    weather_panel: [40, 40, 40] # 天気パネルの背景色
    weather_panel_alpha: 200    # 天気パネルの透明度

# カレンダー設定
calendar:
  first_weekday: "SUNDAY"  # 週の始まり (SUNDAY or MONDAY)
  holidays_enabled: true   # 祝日表示のON/OFF
  holidays_country: "JP"   # 国コード（JP=日本）
  show_holiday_names: false # 祝日名の表示（true=表示, false=色のみ）
  rokuyou_enabled: true    # 六曜表示のON/OFF
  show_rokuyou_names: true # 六曜名の表示（true=表示, false=色のみ）
  rokuyou_format: "single" # 六曜の表示形式（"full", "short", "single"）
  moon_phase_enabled: true # 月相表示のON/OFF
  moon_phase_format: "emoji" # 月相の表示形式（"emoji", "text", "ascii"）

# 背景設定
background:
  dir: "./wallpapers"      # 壁紙ディレクトリ
  mode: "fit"              # 表示モード (fit or fill)
  rescan_sec: 300          # 壁紙切替間隔（秒）

# 天気設定
weather:
  provider: "openmeteo"    # 天気プロバイダ
  refresh_sec: 1800        # 更新間隔（秒）= 30分
  timeout_sec: 10          # タイムアウト（秒）
  location:
    # 東京の座標（お住まいの地域に変更してください）
    lat: 35.681236         # 緯度
    lon: 139.767125        # 経度

# キャラクター設定（オプション）
character:
  enabled: false           # キャラクター表示（true で有効化）
  sprite: "./assets/sprites/char_idle.png"
  frame_width: 128         # フレーム幅
  frame_height: 128        # フレーム高さ
  fps: 8                   # アニメーションFPS

# フォント設定
fonts:
  main:
    path: "./assets/fonts/NotoSansCJK-Regular.otf"
    fallback: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.otf"

# ログ設定
logging:
  level: "INFO"            # ログレベル (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

# 主要都市の座標（参考）
# location設定の参考にしてください
#
# 東京:    lat: 35.681236, lon: 139.767125
# 大阪:    lat: 34.693725, lon: 135.502254
# 名古屋:  lat: 35.181446, lon: 136.906398
# 札幌:    lat: 43.064301, lon: 141.346874
# 仙台:    lat: 38.268215, lon: 140.869356
# 横浜:    lat: 35.443707, lon: 139.638031
# 京都:    lat: 35.011635, lon: 135.768036
# 神戸:    lat: 34.690083, lon: 135.195511
# 広島:    lat: 34.396033, lon: 132.459622
# 福岡:    lat: 33.590355, lon: 130.401716
# 那覇:    lat: 26.212401, lon: 127.680932